#!/bin/bash

CONFIG_FILE="./configure.json"
SERVERS_DIR="./dn/servers"

function usage {
  cat <<EOT
Usage: beeDBd [start|stop|restart|status|stats]
EOT
  exit $1
}

function start_servers {
  echo "Starting RP..."
  node rp/rp_4000.js &

  echo "Starting DN Servers..."
  for port in $(jq -r '.nodes[].servers[].port' $CONFIG_FILE); do
    node $SERVERS_DIR/server_$port.js &
  done

  echo "beeDB started."
}

function stop_servers {
  echo "Stopping all beeDB services..."
  pkill -f rp/rp_4000.js
  pkill -f dn/server_3000.js
  pkill -f dn/server_3110.js
  pkill -f dn/server_3120.js
  pkill -f dn/server_3200.js
  pkill -f dn/server_3210.js
  pkill -f dn/server_3220.js
  echo "Stopped."
}

function show_status {
  echo "Status:"
  pgrep -af server.js
}

function show_stats {
  echo "Stats (mock):"
  echo "Total inserts: 0"
  echo "Total reads: 0"
}

case $1 in
  start) start_servers;;
  stop) stop_servers;;
  restart) stop_servers && sleep 1 && start_servers;;
  status) show_status;;
  stats) show_stats;;
  -h) usage 0;;
  *) usage 1;;
esac
