#version: '3'

services:
  dn0-0:
    build:
      context: .
      dockerfile: ./dn/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    command: ["node", "servers/server_3000.js"]
    working_dir: /app/dn
    depends_on:
      - dn1-0
      - rp
    environment:
      - DOCKER_ENV=true

  dn0-1:
    build:
      context: .
      dockerfile: ./dn/Dockerfile
    ports:
      - "3010:3010"
    volumes:
      - ./:/app
    command: ["node", "servers/server_3010.js"]
    working_dir: /app/dn
    depends_on:
      - dn1-1
      - rp
    environment:
      - DOCKER_ENV=true

  dn0-2:
    build:
      context: .
      dockerfile: ./dn/Dockerfile
    ports:
      - "3020:3020"
    volumes:
      - ./:/app
    command: ["node", "servers/server_3020.js"]
    working_dir: /app/dn
    depends_on:
      - dn1-2
      - rp
    environment:
      - DOCKER_ENV=true

  dn1-0:
    build:
      context: .
      dockerfile: ./dn/Dockerfile
    ports:
      - "3100:3100"
    volumes:
      - ./:/app
    command: ["node", "servers/server_3100.js"]
    working_dir: /app/dn
    depends_on:
      - rp
    environment:
      - DOCKER_ENV=true

  dn1-1:
    build:
      context: .
      dockerfile: ./dn/Dockerfile
    ports:
      - "3110:3110"
    volumes:
      - ./:/app
    command: ["node", "servers/server_3110.js"]
    working_dir: /app/dn
    depends_on:
      - rp
    environment:
      - DOCKER_ENV=true

  dn1-2:
    build:
      context: .
      dockerfile: ./dn/Dockerfile
    ports:
      - "3120:3120"
    volumes:
      - ./:/app
    command: ["node", "servers/server_3120.js"]
    working_dir: /app/dn
    depends_on:
      - rp
    environment:
      - DOCKER_ENV=true

  rp:
    build:
      context: .
      dockerfile: ./rp/Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./:/app
    environment:
      - DOCKER_ENV=true


networks:
  beedbnet:
    driver: bridge
